version: 2
updates:
  # NPM dependencies - grouped by type
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly' # Changed from weekly to monthly
      day: 'tuesday'
      time: '09:00'
    open-pull-requests-limit: 3 # Reduced from 5 to 3
    groups:
      # Group ALL dependencies together to create single PR
      all-npm-dependencies:
        patterns:
          - '*' # Match all packages
        update-types:
          - 'minor'
          - 'patch'
      # Major updates still separate for safety
      major-updates:
        patterns:
          - '*'
        update-types:
          - 'major'

    ignore:
      # Major updates need manual review
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: '@tauri-apps/*'
        update-types: ['version-update:semver-major']

    labels:
      - 'dependencies'
      - 'npm'
      - 'automated'

    reviewers:
      - 'meinzeug'

    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Cargo dependencies
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'monthly' # Changed from weekly to monthly
      day: 'wednesday'
      time: '09:00'
    open-pull-requests-limit: 2 # Reduced from 3 to 2
    groups:
      # Group ALL Rust dependencies together
      all-cargo-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

    ignore:
      # Critical dependencies - manual review
      - dependency-name: 'tauri'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tokio'
        update-types: ['version-update:semver-major']

    labels:
      - 'dependencies'
      - 'rust'
      - 'automated'

    reviewers:
      - 'meinzeug'

    commit-message:
      prefix: 'chore(rust)'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly' # Changed from weekly to monthly
      day: 'thursday'
      time: '09:00'
    open-pull-requests-limit: 1 # Reduced from 2 to 1
    labels:
      - 'dependencies'
      - 'ci/cd'
      - 'automated'

    reviewers:
      - 'meinzeug'

    commit-message:
      prefix: 'ci'
      include: 'scope'
