version: 2
updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'npm'
      prefix-development: 'npm(dev)'
      include: 'scope'
    labels:
      - 'javascript'
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
    groups:
      react:
        patterns:
          - 'react*'
          - '@types/react*'
      testing:
        patterns:
          - '*jest*'
          - '@testing-library/*'
          - 'playwright*'
      build-tools:
        patterns:
          - 'vite*'
          - '@vitejs/*'
          - 'rollup*'
          - 'esbuild*'
      linting:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'

  # Cargo dependencies
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'cargo'
      include: 'scope'
    labels:
      - 'rust'
    ignore:
      # Ignore major version updates for Tauri
      - dependency-name: 'tauri'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tauri-build'
        update-types: ['version-update:semver-major']
    groups:
      tauri:
        patterns:
          - 'tauri*'
      serde:
        patterns:
          - 'serde*'
      async:
        patterns:
          - 'tokio*'
          - 'async-*'
          - 'futures*'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'ci'
    groups:
      setup-actions:
        patterns:
          - 'actions/setup-*'
      cache-actions:
        patterns:
          - 'actions/cache*'
      security-actions:
        patterns:
          - 'github/codeql-action*'
          - 'ossf/scorecard-action*'

  # Docker
  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '09:00'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'docker'
    labels:
      - 'docker'
