version: 2
updates:
  # NPM dependencies - Enhanced for security issue creation
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily' # Daily updates for faster security response
      time: '09:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10 # Increased for security updates
    groups:
      # SECURITY UPDATES - Highest Priority (separate PR)
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'

      # DEVELOPMENT DEPENDENCIES - Safe for auto-merge
      dev-dependencies:
        patterns:
          - '@types/*'
          - '@testing-library/*'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - '@vitejs/*'
          - '@vitest/*'
          - 'eslint*'
          - 'prettier'
          - 'husky'
          - 'lint-staged'
          - 'jest*'
          - 'vitest*'
          - 'playwright*'
        update-types:
          - 'minor'
          - 'patch'

      # PRODUCTION DEPENDENCIES - Minor/Patch updates only
      prod-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - '@testing-library/*'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - '@vitejs/*'
          - '@vitest/*'
          - 'eslint*'
          - 'prettier'
          - 'husky'
          - 'lint-staged'
          - 'jest*'
          - 'vitest*'
          - 'playwright*'
        update-types:
          - 'minor'
          - 'patch'

      # MAJOR UPDATES - Manual review required
      major-updates:
        patterns:
          - '*'
        update-types:
          - 'major'

    ignore:
      # Critical dependencies requiring manual review for major updates
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: '@tauri-apps/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tailwindcss'
        update-types: ['version-update:semver-major']

    labels:
      - 'dependencies'
      - 'npm'
      - 'automated'

    reviewers:
      - 'meinzeug'

    assignees:
      - 'meinzeug'

    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  # Cargo dependencies - OPTIMIZED for daily updates
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'daily' # OPTIMIZED: Daily updates
      time: '09:30' # Staggered 30 minutes after npm
    open-pull-requests-limit: 4 # Increased for daily processing
    groups:
      # SECURITY UPDATES - Highest Priority
      cargo-security-updates:
        applies-to: security-updates
        patterns:
          - '*'

      # DEVELOPMENT/BUILD DEPENDENCIES
      cargo-dev-dependencies:
        patterns:
          - 'serde*'
          - 'clap*'
          - 'anyhow'
          - 'thiserror'
          - 'tracing*'
          - 'log'
          - 'env_logger'
        update-types:
          - 'minor'
          - 'patch'

      # TAURI ECOSYSTEM - Grouped together
      tauri-ecosystem:
        patterns:
          - 'tauri*'
          - '@tauri-apps/*'
        update-types:
          - 'minor'
          - 'patch'

      # OTHER PRODUCTION DEPENDENCIES
      cargo-prod-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'serde*'
          - 'clap*'
          - 'anyhow'
          - 'thiserror'
          - 'tracing*'
          - 'log'
          - 'env_logger'
          - 'tauri*'
          - '@tauri-apps/*'
        update-types:
          - 'minor'
          - 'patch'

    ignore:
      # Critical dependencies requiring manual review
      - dependency-name: 'tauri'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tokio'
        update-types: ['version-update:semver-major']
      - dependency-name: 'serde'
        update-types: ['version-update:semver-major']
      - dependency-name: 'reqwest'
        update-types: ['version-update:semver-major']

    labels:
      - 'dependencies'
      - 'rust'
      - 'automated'
      - 'auto-merge-candidate'

    reviewers:
      - 'meinzeug'

    commit-message:
      prefix: 'chore(deps-rust)'
      include: 'scope'

  # GitHub Actions - OPTIMIZED for daily updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily' # OPTIMIZED: Daily updates
      time: '10:00' # Staggered 1 hour after npm
    open-pull-requests-limit: 3 # Increased for daily processing
    groups:
      # GROUP ALL GitHub Actions together - they're usually safe
      github-actions-all:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
          - 'major' # Actions updates are typically safe

    labels:
      - 'dependencies'
      - 'ci/cd'
      - 'automated'
      - 'auto-merge-candidate' # Safe for auto-merge

    reviewers:
      - 'meinzeug'

    commit-message:
      prefix: 'ci(deps)'
      include: 'scope'
