apiVersion: v1
kind: Namespace
metadata:
  name: autodev-ai
  labels:
    app.kubernetes.io/name: autodev-ai
    app.kubernetes.io/managed-by: kubectl
    kubernetes.io/managed-by: autodev-ai-operator
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: autodev-ai-quota
  namespace: autodev-ai
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: autodev-ai-limits
  namespace: autodev-ai
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container