apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodev-ai
  namespace: autodev-production
  labels:
    app: autodev-ai
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: autodev-ai
      environment: production
  template:
    metadata:
      labels:
        app: autodev-ai
        environment: production
    spec:
      containers:
      - name: autodev-ai
        image: IMAGE_TAG
        ports:
        - containerPort: 50000
          name: main
        - containerPort: 50001
          name: metrics
        - containerPort: 50002
          name: health
        env:
        - name: RUST_LOG
          value: "warn"
        - name: ENVIRONMENT
          value: "production"
        - name: AUTODEV_PORT_RANGE
          value: "50000-50100"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: autodev-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: autodev-secrets
              key: redis-url
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: autodev-secrets
              key: claude-api-key
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: cache
          mountPath: /app/cache
        - name: config
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /health
            port: 50002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 50002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: autodev-data
      - name: cache
        emptyDir:
          sizeLimit: 2Gi
      - name: config
        configMap:
          name: autodev-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: autodev-ai
              topologyKey: kubernetes.io/hostname