apiVersion: v1
kind: Secret
metadata:
  name: autodevai-secrets
  namespace: autodevai
  labels:
    app.kubernetes.io/name: autodevai
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  POSTGRES_PASSWORD: "autodevai_k8s_secure_2024"
  DATABASE_URL: "postgresql://autodevai:autodevai_k8s_secure_2024@postgres-service:5432/autodevai"
  
  # Redis credentials
  REDIS_PASSWORD: "autodevai_redis_k8s_2024"
  REDIS_URL: "redis://:autodevai_redis_k8s_2024@redis-service:6379"
  
  # API Keys (to be replaced with actual values)
  ANTHROPIC_API_KEY: "sk-ant-api03-..."
  OPENAI_API_KEY: "sk-..."
  
  # JWT Secret
  JWT_SECRET: "autodevai_jwt_production_secret_2024_k8s"
  
  # Grafana Admin
  GF_SECURITY_ADMIN_PASSWORD: "autodevai_grafana_admin_2024"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: autodevai
  labels:
    app.kubernetes.io/name: autodevai
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace with actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...