name: Create Issue on Workflow Failure

on:
  workflow_run:
    workflows:
      - "Main CI/CD Pipeline"
      - "PR Validation"
      - "Release Pipeline"
    types:
      - completed

permissions:
  issues: write
  contents: read

jobs:
  create-issue-on-failure:
    name: Create Issue if Workflow Failed
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Check for existing issue
        id: check-issue
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow_name = context.payload.workflow_run.name;
            const run_id = context.payload.workflow_run.id;
            
            // Search for existing open issues
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ci-failure,automated'
            });
            
            // Check if issue already exists for this workflow
            const existingIssue = issues.data.find(issue => 
              issue.title.includes(workflow_name) && 
              issue.body.includes(run_id)
            );
            
            if (existingIssue) {
              console.log(`Issue already exists: #${existingIssue.number}`);
              return existingIssue.number;
            }
            
            return null;

      - name: Create failure issue
        if: steps.check-issue.outputs.result == 'null'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Safely extract data from GitHub context without environment variable injection
            const workflow_name = context.payload.workflow_run.name || 'Unknown Workflow';
            const workflow_url = context.payload.workflow_run.html_url || '';
            const run_id = context.payload.workflow_run.id || '';
            const run_number = context.payload.workflow_run.run_number || '';
            const commit_sha = context.payload.workflow_run.head_sha || '';
            // Sanitize potentially malicious commit message and author
            const commit_message = (context.payload.workflow_run.head_commit?.message || 'No commit message').replace(/[`$(){}[\]|&;<>]/g, '').substring(0, 200);
            const author = (context.payload.workflow_run.head_commit?.author?.name || 'Unknown Author').replace(/[`$(){}[\]|&;<>]/g, '').substring(0, 50);
            const branch = (context.payload.workflow_run.head_branch || 'unknown').replace(/[`$(){}[\]|&;<>]/g, '').substring(0, 100);
            const event_type = context.payload.workflow_run.event || 'unknown';
            const created_at = context.payload.workflow_run.created_at || new Date().toISOString();
            
            // Get workflow run details
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run_id
            });
            
            // Get failed jobs
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run_id,
              filter: 'latest'
            });
            
            const failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');
            
            // Build error details
            let errorDetails = '';
            for (const job of failedJobs) {
              errorDetails += `\n### ❌ Failed Job: ${job.name}\n`;
              errorDetails += `- **Status**: ${job.status}\n`;
              errorDetails += `- **Started**: ${job.started_at}\n`;
              errorDetails += `- **Duration**: ${Math.round((new Date(job.completed_at) - new Date(job.started_at)) / 1000)}s\n`;
              errorDetails += `- **URL**: ${job.html_url}\n`;
              
              // Get failed steps
              const failedSteps = job.steps.filter(step => step.conclusion === 'failure');
              if (failedSteps.length > 0) {
                errorDetails += `\n**Failed Steps:**\n`;
                for (const step of failedSteps) {
                  errorDetails += `- ⚠️ ${step.name} (${step.conclusion})\n`;
                }
              }
            }
            
            // Create issue title and body with sanitized data
            const issueTitle = `🚨 CI/CD Failure: ${workflow_name} (Run #${run_number})`;
            
            const issueBody = `## 🔴 Workflow Failure Detected
            
            The **${workflow_name}** workflow has failed and requires attention.
            
            ### 📊 Workflow Information
            - **Workflow**: ${workflow_name}
            - **Run Number**: #${run_number}
            - **Run ID**: ${run_id}
            - **Branch**: \`${branch}\`
            - **Event**: ${event_type}
            - **Created**: ${created_at}
            - **URL**: [View Workflow Run](${workflow_url})
            
            ### 💻 Commit Information
            - **SHA**: \`${commit_sha.substring(0, 7)}\`
            - **Author**: ${author}
            - **Message**: ${commit_message.split('\n')[0]}
            
            ${errorDetails}
            
            ### 🔧 Suggested Actions
            1. Review the [failed workflow run](${workflow_url})
            2. Check the error logs for specific failure reasons
            3. Fix the identified issues
            4. Push the fixes to trigger a new workflow run
            5. Close this issue once the workflow passes
            
            ### 🏷️ Labels
            This issue has been automatically labeled with:
            - \`ci-failure\`: Indicates a CI/CD pipeline failure
            - \`automated\`: Created by automated workflow
            - \`priority-high\`: Requires immediate attention
            
            ### 🤖 Automation
            This issue was automatically created by the CI/CD failure detection system.
            
            ---
            *Generated at: ${new Date().toISOString()}*
            *Workflow Run: [${run_id}](${workflow_url})*`;
            
            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['ci-failure', 'automated', 'priority-high', 'bug'],
              assignees: []
            });
            
            console.log(`Created issue #${issue.data.number}: ${issue.data.html_url}`);
            
            // Add comment with additional context if needed
            if (failedJobs.length > 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.data.number,
                body: `⚠️ **Multiple job failures detected** (${failedJobs.length} jobs failed)\n\nThis indicates a systemic issue that may require broader investigation.`
              });
            }

      - name: Notify about existing issue
        if: steps.check-issue.outputs.result != 'null'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          # SECURITY FIX: Use environment variables to prevent script injection
          ISSUE_NUMBER: ${{ steps.check-issue.outputs.result }}
          WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
          RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // SECURITY: Get values from environment variables instead of direct interpolation
            const issue_number = process.env.ISSUE_NUMBER || '';
            const workflow_url = process.env.WORKFLOW_URL || '';
            const run_number = process.env.RUN_NUMBER || '';
            
            // Add comment to existing issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `🔄 **Another failure detected**\n\nWorkflow run #${run_number} has also failed.\n[View Workflow Run](${workflow_url})\n\n*Failure detected at: ${new Date().toISOString()}*`
            });
            
            console.log(`Updated existing issue #${issue_number}`);