name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  # Analyze PR changes
  analyze:
    name: PR Analysis
    runs-on: ubuntu-22.04
    outputs:
      skip_ci: ${{ steps.check.outputs.skip_ci }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for skip CI
        id: check
        run: |
          if git log -1 --pretty=%B | grep -q "\[skip ci\]\|\[ci skip\]"; then
            echo "skip_ci=true" >> $GITHUB_OUTPUT
            echo "⏭️ Skipping CI as requested"
          else
            echo "skip_ci=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Get changed files
        id: changed
        run: |
          echo "Changed files:"
          git diff --name-only origin/main...HEAD || git diff --name-only HEAD~1

  # Quick validation
  validate:
    name: Quick Validation
    runs-on: ubuntu-22.04
    needs: analyze
    if: needs.analyze.outputs.skip_ci != 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Type check
        run: npm run typecheck
      
      - name: Format check
        run: npm run format:check || true
      
      - name: Create issue on failure
        if: failure()
        uses: ./.github/actions/create-failure-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          job-name: 'PR Validation'
          workflow-name: 'PR Validation'
          error-message: 'PR validation failed - TypeScript or formatting issues'
          labels: 'ci-failure,pr,automated'

  # Run essential tests only
  test:
    name: Essential Tests
    runs-on: ubuntu-22.04
    needs: [analyze, validate]
    if: needs.analyze.outputs.skip_ci != 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm test || npm run test:run || true
      
      - name: Create issue on failure
        if: failure()
        uses: ./.github/actions/create-failure-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          job-name: 'Essential Tests'
          workflow-name: 'PR Validation'
          error-message: 'PR tests failed'
          labels: 'ci-failure,pr,tests,automated'

  # Quick build check
  build:
    name: Build Check
    runs-on: ubuntu-22.04
    needs: [analyze, validate]
    if: needs.analyze.outputs.skip_ci != 'true'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build frontend
        run: npm run build
      
      - name: Check build size
        run: |
          echo "Build size:"
          du -sh dist/ || true
      
      - name: Create issue on failure
        if: failure()
        uses: ./.github/actions/create-failure-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          job-name: 'Build Check'
          workflow-name: 'PR Validation'
          error-message: 'PR build failed'
          labels: 'ci-failure,pr,build,automated'

  # PR status summary
  pr-status:
    name: PR Status
    runs-on: ubuntu-22.04
    needs: [analyze, validate, test, build]
    if: always()
    steps:
      - name: PR validation summary
        uses: actions/github-script@v7
        env:
          SKIP_CI: ${{ needs.analyze.outputs.skip_ci }}
          VALIDATE_RESULT: ${{ needs.validate.result }}
          TEST_RESULT: ${{ needs.test.result }}
          BUILD_RESULT: ${{ needs.build.result }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const skipCI = process.env.SKIP_CI === 'true';
            
            if (skipCI) {
              console.log('⏭️ CI skipped by request');
              return;
            }
            
            const results = {
              validate: process.env.VALIDATE_RESULT,
              test: process.env.TEST_RESULT,
              build: process.env.BUILD_RESULT
            };
            
            let comment = '## 📋 PR Validation Results\n\n';
            let allPassed = true;
            
            for (const [job, result] of Object.entries(results)) {
              const emoji = result === 'success' ? '✅' : 
                           result === 'failure' ? '❌' : '⏭️';
              comment += `${emoji} **${job}**: ${result}\n`;
              if (result === 'failure') allPassed = false;
            }
            
            comment += '\n';
            comment += allPassed ? 
              '### ✅ All checks passed! Ready for review.' :
              '### ⚠️ Some checks failed. Please fix the issues before merging.';
            
            // Post comment on PR
            if (context.issue.number) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }